### ISSUE TITLE
add RNCookieManagerIOS.h and RNCookieManagerIOS.m to your ios project

### ISSUE THREAD

**Issue by jayshah123** [react-native-community/cookies#37]
# Bug
Error "add RNCookieManagerIOS.h and RNCookieManagerIOS.m to your ios project"

<img width="342" alt="Screenshot 2020-02-28 at 8 22 03 PM" src="https://user-images.githubusercontent.com/659202/75558566-037f6280-5a68-11ea-86a2-fc5a02452085.png">

## Environment info
 
react-native-community/cookies version: 2.0.3
React native info output:

```bash
System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 700.00 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 25.0.0, 27.0.3, 28.0.1, 28.0.3, 29.0.0, 29.0.3
      System Images: android-19 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-25 | Google Play Intel x86 Atom, android-26 | Google Play Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom
      Android NDK: 17.2.4988734
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5
```

Library version: 2.0.3

react-native config already contains this package:
```
    "@react-native-community/cookies": {
      "root": "/Users/jay.shah/Documents/mypartner/node_modules/@react-native-community/cookies",
      "name": "@react-native-community/cookies",
      "platforms": {
        "ios": {
          "sourceDir": "/Users/jay.shah/Documents/mypartner/node_modules/@react-native-community/cookies/ios",
          "folder": "/Users/jay.shah/Documents/mypartner/node_modules/@react-native-community/cookies",
          "pbxprojPath": "/Users/jay.shah/Documents/mypartner/node_modules/@react-native-community/cookies/ios/RNCookieManagerIOS.xcodeproj/project.pbxproj",
          "podfile": null,
          "podspecPath": "/Users/jay.shah/Documents/mypartner/node_modules/@react-native-community/cookies/ios/react-native-cookies.podspec",
          "projectPath": "/Users/jay.shah/Documents/mypartner/node_modules/@react-native-community/cookies/ios/RNCookieManagerIOS.xcodeproj",
          "projectName": "RNCookieManagerIOS.xcodeproj",
          "libraryFolder": "Libraries",
          "sharedLibraries": [],
          "plist": [],
          "scriptPhases": []
        },
        "android": {
          "sourceDir": "/Users/jay.shah/Documents/mypartner/node_modules/@react-native-community/cookies/android",
          "folder": "/Users/jay.shah/Documents/mypartner/node_modules/@react-native-community/cookies",
          "packageImportPath": "import com.reactnativecommunity.cookies.CookieManagerPackage;",
          "packageInstance": "new CookieManagerPackage()"
        }
      },
      "assets": [],
      "hooks": {},
      "params": []
    },
```

## Steps To Reproduce

1. npm install --save @react-native-community/cookies
2. pod install
3. run app from Xcode

Describe what you expected to happen:

1. ios build to work but breaks with "add RNCookieManagerIOS.h and RNCookieManagerIOS.m to your ios project"

**Comment by jayshah123** [comment]
Library only works if I add `pod 'react-native-cookies', :path => '../node_modules/react-native-cookies/ios'` in Podfile

**Comment by jayshah123** [comment]
Only works when I add
```
pod 'react-native-cookies', :path => '../node_modules/@react-native-community/cookies/ios'
```
to my Podfile.
Ideally library should work without adding the above line right?

**Comment by safaiyeh** [comment]
Hmm @jayshah123 it possible might be due to the podspec being in the iOS/ folder and at the root. Could you try that locally and possible send a PR for that?

**Comment by jayshah123** [comment]
will check this

**Comment by nareshbhatia** [comment]
I am getting the same error when running jest. I also added the 'react-native-cookies' line mentioned above to Podfile (and ran pod install), but that made no difference.

**Comment by safaiyeh** [comment]
Fixed with https://github.com/react-native-community/cookies/pull/40

**Comment by remy90** [comment]
I still have this issue in jest, @nareshbhatia any luck resolving this?

**Comment by nareshbhatia** [comment]
@remy90, sorry I am not on that project any more and can't remember if we had solved the issue.

**Comment by luisaverza** [comment]
Hi @remy90 

I just solved this issue configuring jest with a [setupFile](https://jestjs.io/docs/en/configuration#setupfiles-array).
Inside the `setupFile` you should create a mock for this library:

```
jest.mock('@react-native-community/cookies', () => ({
  CookieManager: jest.fn(),
}));
```

**Comment by dwesty17** [comment]
Thanks for the help @luisaverza! I had to do it slightly differently just given some of the changes to the library...

```tsx
jest.mock("@react-native-cookies/cookies", () => ({
  clearAll: jest.fn(),
}));
```

just incase anyone else stumbles across this thread.

**Comment by vijayaumar-eswaramur** [comment]
I solved this issue by doing following:
(Delete installed app)
1. Clean XCode Project
2. Build XCode Project

**Comment by brysonjonesy** [comment]
This worked for me in a jestSetup file:
```
jest.mock('@react-native-community/cookies', () => ({
  CookieManager: jest.fn(),
}));

**Comment by dcsan** [comment]
I'm getting this - not with jest just normal trying to run the RN app.

with adding 
`pod 'react-native-cookies', :path => '../node_modules/@react-native-community/cookies/ios'`

I now get:

[!] No podspec found for `react-native-cookies` in `../node_modules/@react-native-community/cookies/ios`
